// Bot javoblari (uz/ru/en). Buyruqlar lotincha — Telegram talabi.
import type { Locale } from '../_shared/money.ts'

export const BOT_TEXT = {
  uz: {
    linked: '✅ My Wallet ulandi. Eslatmalar va hisobotlar endi shu yerga keladi.',
    token_invalid: "Havola noto'g'ri. Ilovada Sozlamalar → Telegram → «Ulash» ni qayta bosing.",
    token_used: 'Bu havola allaqachon ishlatilgan. Ilovada yangi havola oling.',
    token_expired: "Havola muddati o'tgan. Ilovada yangi havola oling.",
    unlinked: 'Bot uzildi. Qayta ulash — ilovada Sozlamalar → Telegram.',
    not_linked: 'Avval ilovada Sozlamalar → Telegram → «Ulash» orqali ulaning.',
    help: "My Wallet boti.\n/balans — joriy oy qoldig'i\n/bugun — bugungi va muddati o'tgan to'lovlar\n/stop — uzish",
    income: 'Daromad',
    expense: 'Xarajat',
    balance: 'Qoldiq',
    forecast: 'Prognoz',
    todayTitle: "📌 To'lovlar (bugun va kechikkan)",
    nothingToday: "Bugun to'lov yo'q ✅",
    variable: "summa o'zgaruvchi",
  },
  ru: {
    linked: '✅ My Wallet подключён. Напоминания и отчёты теперь будут приходить сюда.',
    token_invalid: 'Ссылка неверна. В приложении: Настройки → Telegram → «Подключить».',
    token_used: 'Эта ссылка уже использована. Получите новую в приложении.',
    token_expired: 'Срок действия ссылки истёк. Получите новую в приложении.',
    unlinked: 'Бот отключён. Подключить снова — в приложении: Настройки → Telegram.',
    not_linked: 'Сначала подключите бота в приложении: Настройки → Telegram → «Подключить».',
    help: 'Бот My Wallet.\n/balans — остаток за месяц\n/bugun — платежи на сегодня и просроченные\n/stop — отключить',
    income: 'Доход',
    expense: 'Расход',
    balance: 'Остаток',
    forecast: 'Прогноз',
    todayTitle: '📌 Платежи (сегодня и просроченные)',
    nothingToday: 'Сегодня платежей нет ✅',
    variable: 'сумма меняется',
  },
  en: {
    linked: '✅ My Wallet is connected. Reminders and reports will arrive here.',
    token_invalid: 'The link is invalid. In the app: Settings → Telegram → “Connect”.',
    token_used: 'This link has already been used. Get a new one in the app.',
    token_expired: 'The link has expired. Get a new one in the app.',
    unlinked: 'The bot is disconnected. Reconnect in the app: Settings → Telegram.',
    not_linked: 'Connect the bot first in the app: Settings → Telegram → “Connect”.',
    help: "My Wallet bot.\n/balans — this month's balance\n/bugun — payments due today and overdue\n/stop — disconnect",
    income: 'Income',
    expense: 'Expenses',
    balance: 'Balance',
    forecast: 'Forecast',
    todayTitle: '📌 Payments (today and overdue)',
    nothingToday: 'No payments today ✅',
    variable: 'amount varies',
  },
} as const satisfies Record<Locale, Record<string, string>>
