// Bot javoblari (uz/ru/en). Buyruqlar lotincha — Telegram talabi.
import type { Locale } from '../_shared/money.ts'

export const BOT_TEXT = {
  uz: {
    linked: '✅ My Wallet ulandi. Eslatmalar va hisobotlar endi shu yerga keladi.',
    token_invalid: "Havola noto'g'ri. Ilovada Sozlamalar → Telegram → «Ulash» ni qayta bosing.",
    token_used: 'Bu havola allaqachon ishlatilgan. Ilovada yangi havola oling.',
    token_expired: "Havola muddati o'tgan. Ilovada yangi havola oling.",
    unlinked: 'Bot uzildi. Qayta ulash — ilovada Sozlamalar → Telegram.',
    not_linked: 'Avval ilovada Sozlamalar → Telegram → «Ulash» orqali ulaning.',
    help:
      "My Wallet boti.\n/balans — joriy oy qoldig'i\n/bugun — bugungi va muddati o'tgan to'lovlar\n/hisobot [oy] — oylik yakun\n/til uz|ru|en — til\n/stop — uzish\n\nTez kiritish: `taksi 20000`, `+5 000 000 oylik`",
    income: 'Daromad',
    expense: 'Xarajat',
    balance: 'Qoldiq',
    forecast: 'Prognoz',
    todayTitle: "📌 To'lovlar (bugun va kechikkan)",
    nothingToday: "Bugun to'lov yo'q ✅",
    variable: "summa o'zgaruvchi",
    saved: '✅ Yozildi',
    editCategory: '✏️ Kategoriya',
    cancel: '❌ Bekor qilish',
    chooseCategory: 'Kategoriyani tanlang:',
    categoryUpdated: 'Kategoriya:',
    undone: '❌ Bekor qilindi',
    notFound: 'Amal topilmadi (allaqachon o‘chirilgan bo‘lishi mumkin).',
    setupRequired: 'Avval ilovada hisob va kategoriya yarating.',
    monthClosed: 'Bu oy yopilgan — amal yozilmadi.',
    writeFailed: 'Yozib bo‘lmadi. Ilovada urinib ko‘ring.',
    quickHint: 'Masalan: `taksi 20000` yoki `+5 000 000 oylik`',
    savedLabel: 'Orttirgan',
    cardNoTemplate: 'Bu xabar uchun shablon topilmadi. Admin panelda shablon qo‘shing.',
    langChanged: '✅ Til o‘zgartirildi.',
    langUsage: 'Til: /til uz | ru | en',
  },
  ru: {
    linked: '✅ My Wallet подключён. Напоминания и отчёты теперь будут приходить сюда.',
    token_invalid: 'Ссылка неверна. В приложении: Настройки → Telegram → «Подключить».',
    token_used: 'Эта ссылка уже использована. Получите новую в приложении.',
    token_expired: 'Срок действия ссылки истёк. Получите новую в приложении.',
    unlinked: 'Бот отключён. Подключить снова — в приложении: Настройки → Telegram.',
    not_linked: 'Сначала подключите бота в приложении: Настройки → Telegram → «Подключить».',
    help:
      'Бот My Wallet.\n/balans — остаток за месяц\n/bugun — платежи на сегодня и просроченные\n/hisobot [месяц] — итоги месяца\n/til uz|ru|en — язык\n/stop — отключить\n\nБыстрый ввод: `такси 20000`, `+5 000 000 зарплата`',
    income: 'Доход',
    expense: 'Расход',
    balance: 'Остаток',
    forecast: 'Прогноз',
    todayTitle: '📌 Платежи (сегодня и просроченные)',
    nothingToday: 'Сегодня платежей нет ✅',
    variable: 'сумма меняется',
    saved: '✅ Записано',
    editCategory: '✏️ Категория',
    cancel: '❌ Отменить',
    chooseCategory: 'Выберите категорию:',
    categoryUpdated: 'Категория:',
    undone: '❌ Отменено',
    notFound: 'Операция не найдена (возможно, уже удалена).',
    setupRequired: 'Сначала создайте счёт и категорию в приложении.',
    monthClosed: 'Месяц закрыт — операция не записана.',
    writeFailed: 'Не удалось записать. Попробуйте в приложении.',
    quickHint: 'Например: `такси 20000` или `+5 000 000 зарплата`',
    savedLabel: 'Накоплено',
    cardNoTemplate: 'Шаблон для этого сообщения не найден. Добавьте его в админке.',
    langChanged: '✅ Язык изменён.',
    langUsage: 'Язык: /til uz | ru | en',
  },
  en: {
    linked: '✅ My Wallet is connected. Reminders and reports will arrive here.',
    token_invalid: 'The link is invalid. In the app: Settings → Telegram → “Connect”.',
    token_used: 'This link has already been used. Get a new one in the app.',
    token_expired: 'The link has expired. Get a new one in the app.',
    unlinked: 'The bot is disconnected. Reconnect in the app: Settings → Telegram.',
    not_linked: 'Connect the bot first in the app: Settings → Telegram → “Connect”.',
    help:
      "My Wallet bot.\n/balans — this month's balance\n/bugun — payments due today and overdue\n/hisobot [month] — monthly summary\n/til uz|ru|en — language\n/stop — disconnect\n\nQuick entry: `taxi 20000`, `+5 000 000 salary`",
    income: 'Income',
    expense: 'Expenses',
    balance: 'Balance',
    forecast: 'Forecast',
    todayTitle: '📌 Payments (today and overdue)',
    nothingToday: 'No payments today ✅',
    variable: 'amount varies',
    saved: '✅ Saved',
    editCategory: '✏️ Category',
    cancel: '❌ Undo',
    chooseCategory: 'Choose a category:',
    categoryUpdated: 'Category:',
    undone: '❌ Undone',
    notFound: 'Transaction not found (it may already be deleted).',
    setupRequired: 'Create an account and a category in the app first.',
    monthClosed: 'The month is closed — nothing was written.',
    writeFailed: 'Could not write it. Try the app.',
    quickHint: 'For example: `taxi 20000` or `+5 000 000 salary`',
    savedLabel: 'Saved',
    cardNoTemplate: 'No template matched this message. Add one in the admin panel.',
    langChanged: '✅ Language changed.',
    langUsage: 'Language: /til uz | ru | en',
  },
} as const satisfies Record<Locale, Record<string, string>>
