export { PlatformAnnouncementsPage } from '@/features/platform/ui/announcements-page'
export { PlatformConfigPage } from '@/features/platform/ui/config-page'
export { PlatformDirectoriesPage } from '@/features/platform/ui/directories-page'
export { PlatformShell } from '@/features/platform/ui/platform-shell'
export { PlatformUsersPage } from '@/features/platform/ui/users-page'
