/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPlatformRouteImport } from './routes/_app/platform'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthMfaRouteImport } from './routes/_auth/mfa'
import { Route as AppHHouseholdIdRouteImport } from './routes/_app/h/$householdId'
import { Route as AppPlatformIndexRouteImport } from './routes/_app/platform/index'
import { Route as AppPlatformAnnouncementsRouteImport } from './routes/_app/platform/announcements'
import { Route as AppPlatformConfigRouteImport } from './routes/_app/platform/config'
import { Route as AppPlatformHealthRouteImport } from './routes/_app/platform/health'
import { Route as AppPlatformRatesRouteImport } from './routes/_app/platform/rates'
import { Route as AppPlatformUsersRouteImport } from './routes/_app/platform/users'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth/auth/callback'
import { Route as AppHHouseholdIdIndexRouteImport } from './routes/_app/h/$householdId/index'
import { Route as AppHHouseholdIdAccountsRouteImport } from './routes/_app/h/$householdId/accounts'
import { Route as AppHHouseholdIdAuditRouteImport } from './routes/_app/h/$householdId/audit'
import { Route as AppHHouseholdIdCategoriesRouteImport } from './routes/_app/h/$householdId/categories'
import { Route as AppHHouseholdIdDebtsRouteImport } from './routes/_app/h/$householdId/debts'
import { Route as AppHHouseholdIdDevicesRouteImport } from './routes/_app/h/$householdId/devices'
import { Route as AppHHouseholdIdExportRouteImport } from './routes/_app/h/$householdId/export'
import { Route as AppHHouseholdIdGoalsRouteImport } from './routes/_app/h/$householdId/goals'
import { Route as AppHHouseholdIdHealthRouteImport } from './routes/_app/h/$householdId/health'
import { Route as AppHHouseholdIdImportRouteImport } from './routes/_app/h/$householdId/import'
import { Route as AppHHouseholdIdLegacyRouteImport } from './routes/_app/h/$householdId/legacy'
import { Route as AppHHouseholdIdLimitsRouteImport } from './routes/_app/h/$householdId/limits'
import { Route as AppHHouseholdIdNotificationsRouteImport } from './routes/_app/h/$householdId/notifications'
import { Route as AppHHouseholdIdPlansRouteImport } from './routes/_app/h/$householdId/plans'
import { Route as AppHHouseholdIdProfileRouteImport } from './routes/_app/h/$householdId/profile'
import { Route as AppHHouseholdIdQuickActionsRouteImport } from './routes/_app/h/$householdId/quick-actions'
import { Route as AppHHouseholdIdRecalcRouteImport } from './routes/_app/h/$householdId/recalc'
import { Route as AppHHouseholdIdRecurringRulesRouteImport } from './routes/_app/h/$householdId/recurring-rules'
import { Route as AppHHouseholdIdReportRouteImport } from './routes/_app/h/$householdId/report'
import { Route as AppHHouseholdIdSettingsRouteImport } from './routes/_app/h/$householdId/settings'
import { Route as AppHHouseholdIdTagsRouteImport } from './routes/_app/h/$householdId/tags'
import { Route as AppHHouseholdIdTransactionsRouteImport } from './routes/_app/h/$householdId/transactions'
import { Route as AppHHouseholdIdReportIndexRouteImport } from './routes/_app/h/$householdId/report.index'
import { Route as AppHHouseholdIdReportCategoriesRouteImport } from './routes/_app/h/$householdId/report.categories'
import { Route as AppHHouseholdIdReportInsightsRouteImport } from './routes/_app/h/$householdId/report.insights'
import { Route as AppHHouseholdIdReportObligationsRouteImport } from './routes/_app/h/$householdId/report.obligations'
import { Route as AppHHouseholdIdReportSavingsRouteImport } from './routes/_app/h/$householdId/report.savings'
import { Route as AppHHouseholdIdReportYearRouteImport } from './routes/_app/h/$householdId/report.year'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AppHHouseholdIdRoute = AppHHouseholdIdRouteImport.update({
  id: '/h/$householdId',
  path: '/h/$householdId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformIndexRoute = AppPlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformAnnouncementsRoute =
  AppPlatformAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AppPlatformRoute,
  } as any)
const AppPlatformConfigRoute = AppPlatformConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformHealthRoute = AppPlatformHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformRatesRoute = AppPlatformRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AppPlatformUsersRoute = AppPlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppPlatformRoute,
} as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppHHouseholdIdIndexRoute = AppHHouseholdIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdAccountsRoute = AppHHouseholdIdAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdAuditRoute = AppHHouseholdIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdCategoriesRoute =
  AppHHouseholdIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdDebtsRoute = AppHHouseholdIdDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdDevicesRoute = AppHHouseholdIdDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdExportRoute = AppHHouseholdIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdGoalsRoute = AppHHouseholdIdGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdHealthRoute = AppHHouseholdIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdImportRoute = AppHHouseholdIdImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdLegacyRoute = AppHHouseholdIdLegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdLimitsRoute = AppHHouseholdIdLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdNotificationsRoute =
  AppHHouseholdIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdPlansRoute = AppHHouseholdIdPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdProfileRoute = AppHHouseholdIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdQuickActionsRoute =
  AppHHouseholdIdQuickActionsRouteImport.update({
    id: '/quick-actions',
    path: '/quick-actions',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdRecalcRoute = AppHHouseholdIdRecalcRouteImport.update({
  id: '/recalc',
  path: '/recalc',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdRecurringRulesRoute =
  AppHHouseholdIdRecurringRulesRouteImport.update({
    id: '/recurring-rules',
    path: '/recurring-rules',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdReportRoute = AppHHouseholdIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdSettingsRoute = AppHHouseholdIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdTagsRoute = AppHHouseholdIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdTransactionsRoute =
  AppHHouseholdIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdReportIndexRoute =
  AppHHouseholdIdReportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppHHouseholdIdReportRoute,
  } as any)
const AppHHouseholdIdReportCategoriesRoute =
  AppHHouseholdIdReportCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppHHouseholdIdReportRoute,
  } as any)
const AppHHouseholdIdReportInsightsRoute =
  AppHHouseholdIdReportInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AppHHouseholdIdReportRoute,
  } as any)
const AppHHouseholdIdReportObligationsRoute =
  AppHHouseholdIdReportObligationsRouteImport.update({
    id: '/obligations',
    path: '/obligations',
    getParentRoute: () => AppHHouseholdIdReportRoute,
  } as any)
const AppHHouseholdIdReportSavingsRoute =
  AppHHouseholdIdReportSavingsRouteImport.update({
    id: '/savings',
    path: '/savings',
    getParentRoute: () => AppHHouseholdIdReportRoute,
  } as any)
const AppHHouseholdIdReportYearRoute =
  AppHHouseholdIdReportYearRouteImport.update({
    id: '/year',
    path: '/year',
    getParentRoute: () => AppHHouseholdIdReportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/platform': typeof AppPlatformRouteWithChildren
  '/welcome': typeof AppWelcomeRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/h/$householdId': typeof AppHHouseholdIdRouteWithChildren
  '/platform/announcements': typeof AppPlatformAnnouncementsRoute
  '/platform/config': typeof AppPlatformConfigRoute
  '/platform/health': typeof AppPlatformHealthRoute
  '/platform/rates': typeof AppPlatformRatesRoute
  '/platform/users': typeof AppPlatformUsersRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/platform/': typeof AppPlatformIndexRoute
  '/h/$householdId/accounts': typeof AppHHouseholdIdAccountsRoute
  '/h/$householdId/audit': typeof AppHHouseholdIdAuditRoute
  '/h/$householdId/categories': typeof AppHHouseholdIdCategoriesRoute
  '/h/$householdId/debts': typeof AppHHouseholdIdDebtsRoute
  '/h/$householdId/devices': typeof AppHHouseholdIdDevicesRoute
  '/h/$householdId/export': typeof AppHHouseholdIdExportRoute
  '/h/$householdId/goals': typeof AppHHouseholdIdGoalsRoute
  '/h/$householdId/health': typeof AppHHouseholdIdHealthRoute
  '/h/$householdId/import': typeof AppHHouseholdIdImportRoute
  '/h/$householdId/legacy': typeof AppHHouseholdIdLegacyRoute
  '/h/$householdId/limits': typeof AppHHouseholdIdLimitsRoute
  '/h/$householdId/notifications': typeof AppHHouseholdIdNotificationsRoute
  '/h/$householdId/plans': typeof AppHHouseholdIdPlansRoute
  '/h/$householdId/profile': typeof AppHHouseholdIdProfileRoute
  '/h/$householdId/quick-actions': typeof AppHHouseholdIdQuickActionsRoute
  '/h/$householdId/recalc': typeof AppHHouseholdIdRecalcRoute
  '/h/$householdId/recurring-rules': typeof AppHHouseholdIdRecurringRulesRoute
  '/h/$householdId/report': typeof AppHHouseholdIdReportRouteWithChildren
  '/h/$householdId/settings': typeof AppHHouseholdIdSettingsRoute
  '/h/$householdId/tags': typeof AppHHouseholdIdTagsRoute
  '/h/$householdId/transactions': typeof AppHHouseholdIdTransactionsRoute
  '/h/$householdId/': typeof AppHHouseholdIdIndexRoute
  '/h/$householdId/report/categories': typeof AppHHouseholdIdReportCategoriesRoute
  '/h/$householdId/report/insights': typeof AppHHouseholdIdReportInsightsRoute
  '/h/$householdId/report/obligations': typeof AppHHouseholdIdReportObligationsRoute
  '/h/$householdId/report/savings': typeof AppHHouseholdIdReportSavingsRoute
  '/h/$householdId/report/year': typeof AppHHouseholdIdReportYearRoute
  '/h/$householdId/report/': typeof AppHHouseholdIdReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/welcome': typeof AppWelcomeRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/platform/announcements': typeof AppPlatformAnnouncementsRoute
  '/platform/config': typeof AppPlatformConfigRoute
  '/platform/health': typeof AppPlatformHealthRoute
  '/platform/rates': typeof AppPlatformRatesRoute
  '/platform/users': typeof AppPlatformUsersRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/platform': typeof AppPlatformIndexRoute
  '/h/$householdId/accounts': typeof AppHHouseholdIdAccountsRoute
  '/h/$householdId/audit': typeof AppHHouseholdIdAuditRoute
  '/h/$householdId/categories': typeof AppHHouseholdIdCategoriesRoute
  '/h/$householdId/debts': typeof AppHHouseholdIdDebtsRoute
  '/h/$householdId/devices': typeof AppHHouseholdIdDevicesRoute
  '/h/$householdId/export': typeof AppHHouseholdIdExportRoute
  '/h/$householdId/goals': typeof AppHHouseholdIdGoalsRoute
  '/h/$householdId/health': typeof AppHHouseholdIdHealthRoute
  '/h/$householdId/import': typeof AppHHouseholdIdImportRoute
  '/h/$householdId/legacy': typeof AppHHouseholdIdLegacyRoute
  '/h/$householdId/limits': typeof AppHHouseholdIdLimitsRoute
  '/h/$householdId/notifications': typeof AppHHouseholdIdNotificationsRoute
  '/h/$householdId/plans': typeof AppHHouseholdIdPlansRoute
  '/h/$householdId/profile': typeof AppHHouseholdIdProfileRoute
  '/h/$householdId/quick-actions': typeof AppHHouseholdIdQuickActionsRoute
  '/h/$householdId/recalc': typeof AppHHouseholdIdRecalcRoute
  '/h/$householdId/recurring-rules': typeof AppHHouseholdIdRecurringRulesRoute
  '/h/$householdId/settings': typeof AppHHouseholdIdSettingsRoute
  '/h/$householdId/tags': typeof AppHHouseholdIdTagsRoute
  '/h/$householdId/transactions': typeof AppHHouseholdIdTransactionsRoute
  '/h/$householdId': typeof AppHHouseholdIdIndexRoute
  '/h/$householdId/report/categories': typeof AppHHouseholdIdReportCategoriesRoute
  '/h/$householdId/report/insights': typeof AppHHouseholdIdReportInsightsRoute
  '/h/$householdId/report/obligations': typeof AppHHouseholdIdReportObligationsRoute
  '/h/$householdId/report/savings': typeof AppHHouseholdIdReportSavingsRoute
  '/h/$householdId/report/year': typeof AppHHouseholdIdReportYearRoute
  '/h/$householdId/report': typeof AppHHouseholdIdReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/platform': typeof AppPlatformRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/mfa': typeof AuthMfaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/h/$householdId': typeof AppHHouseholdIdRouteWithChildren
  '/_app/platform/announcements': typeof AppPlatformAnnouncementsRoute
  '/_app/platform/config': typeof AppPlatformConfigRoute
  '/_app/platform/health': typeof AppPlatformHealthRoute
  '/_app/platform/rates': typeof AppPlatformRatesRoute
  '/_app/platform/users': typeof AppPlatformUsersRoute
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/_app/platform/': typeof AppPlatformIndexRoute
  '/_app/h/$householdId/accounts': typeof AppHHouseholdIdAccountsRoute
  '/_app/h/$householdId/audit': typeof AppHHouseholdIdAuditRoute
  '/_app/h/$householdId/categories': typeof AppHHouseholdIdCategoriesRoute
  '/_app/h/$householdId/debts': typeof AppHHouseholdIdDebtsRoute
  '/_app/h/$householdId/devices': typeof AppHHouseholdIdDevicesRoute
  '/_app/h/$householdId/export': typeof AppHHouseholdIdExportRoute
  '/_app/h/$householdId/goals': typeof AppHHouseholdIdGoalsRoute
  '/_app/h/$householdId/health': typeof AppHHouseholdIdHealthRoute
  '/_app/h/$householdId/import': typeof AppHHouseholdIdImportRoute
  '/_app/h/$householdId/legacy': typeof AppHHouseholdIdLegacyRoute
  '/_app/h/$householdId/limits': typeof AppHHouseholdIdLimitsRoute
  '/_app/h/$householdId/notifications': typeof AppHHouseholdIdNotificationsRoute
  '/_app/h/$householdId/plans': typeof AppHHouseholdIdPlansRoute
  '/_app/h/$householdId/profile': typeof AppHHouseholdIdProfileRoute
  '/_app/h/$householdId/quick-actions': typeof AppHHouseholdIdQuickActionsRoute
  '/_app/h/$householdId/recalc': typeof AppHHouseholdIdRecalcRoute
  '/_app/h/$householdId/recurring-rules': typeof AppHHouseholdIdRecurringRulesRoute
  '/_app/h/$householdId/report': typeof AppHHouseholdIdReportRouteWithChildren
  '/_app/h/$householdId/settings': typeof AppHHouseholdIdSettingsRoute
  '/_app/h/$householdId/tags': typeof AppHHouseholdIdTagsRoute
  '/_app/h/$householdId/transactions': typeof AppHHouseholdIdTransactionsRoute
  '/_app/h/$householdId/': typeof AppHHouseholdIdIndexRoute
  '/_app/h/$householdId/report/categories': typeof AppHHouseholdIdReportCategoriesRoute
  '/_app/h/$householdId/report/insights': typeof AppHHouseholdIdReportInsightsRoute
  '/_app/h/$householdId/report/obligations': typeof AppHHouseholdIdReportObligationsRoute
  '/_app/h/$householdId/report/savings': typeof AppHHouseholdIdReportSavingsRoute
  '/_app/h/$householdId/report/year': typeof AppHHouseholdIdReportYearRoute
  '/_app/h/$householdId/report/': typeof AppHHouseholdIdReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/welcome'
    | '/login'
    | '/mfa'
    | '/h/$householdId'
    | '/platform/announcements'
    | '/platform/config'
    | '/platform/health'
    | '/platform/rates'
    | '/platform/users'
    | '/auth/callback'
    | '/platform/'
    | '/h/$householdId/accounts'
    | '/h/$householdId/audit'
    | '/h/$householdId/categories'
    | '/h/$householdId/debts'
    | '/h/$householdId/devices'
    | '/h/$householdId/export'
    | '/h/$householdId/goals'
    | '/h/$householdId/health'
    | '/h/$householdId/import'
    | '/h/$householdId/legacy'
    | '/h/$householdId/limits'
    | '/h/$householdId/notifications'
    | '/h/$householdId/plans'
    | '/h/$householdId/profile'
    | '/h/$householdId/quick-actions'
    | '/h/$householdId/recalc'
    | '/h/$householdId/recurring-rules'
    | '/h/$householdId/report'
    | '/h/$householdId/settings'
    | '/h/$householdId/tags'
    | '/h/$householdId/transactions'
    | '/h/$householdId/'
    | '/h/$householdId/report/categories'
    | '/h/$householdId/report/insights'
    | '/h/$householdId/report/obligations'
    | '/h/$householdId/report/savings'
    | '/h/$householdId/report/year'
    | '/h/$householdId/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/login'
    | '/mfa'
    | '/platform/announcements'
    | '/platform/config'
    | '/platform/health'
    | '/platform/rates'
    | '/platform/users'
    | '/auth/callback'
    | '/platform'
    | '/h/$householdId/accounts'
    | '/h/$householdId/audit'
    | '/h/$householdId/categories'
    | '/h/$householdId/debts'
    | '/h/$householdId/devices'
    | '/h/$householdId/export'
    | '/h/$householdId/goals'
    | '/h/$householdId/health'
    | '/h/$householdId/import'
    | '/h/$householdId/legacy'
    | '/h/$householdId/limits'
    | '/h/$householdId/notifications'
    | '/h/$householdId/plans'
    | '/h/$householdId/profile'
    | '/h/$householdId/quick-actions'
    | '/h/$householdId/recalc'
    | '/h/$householdId/recurring-rules'
    | '/h/$householdId/settings'
    | '/h/$householdId/tags'
    | '/h/$householdId/transactions'
    | '/h/$householdId'
    | '/h/$householdId/report/categories'
    | '/h/$householdId/report/insights'
    | '/h/$householdId/report/obligations'
    | '/h/$householdId/report/savings'
    | '/h/$householdId/report/year'
    | '/h/$householdId/report'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/platform'
    | '/_app/welcome'
    | '/_auth/login'
    | '/_auth/mfa'
    | '/_app/'
    | '/_app/h/$householdId'
    | '/_app/platform/announcements'
    | '/_app/platform/config'
    | '/_app/platform/health'
    | '/_app/platform/rates'
    | '/_app/platform/users'
    | '/_auth/auth/callback'
    | '/_app/platform/'
    | '/_app/h/$householdId/accounts'
    | '/_app/h/$householdId/audit'
    | '/_app/h/$householdId/categories'
    | '/_app/h/$householdId/debts'
    | '/_app/h/$householdId/devices'
    | '/_app/h/$householdId/export'
    | '/_app/h/$householdId/goals'
    | '/_app/h/$householdId/health'
    | '/_app/h/$householdId/import'
    | '/_app/h/$householdId/legacy'
    | '/_app/h/$householdId/limits'
    | '/_app/h/$householdId/notifications'
    | '/_app/h/$householdId/plans'
    | '/_app/h/$householdId/profile'
    | '/_app/h/$householdId/quick-actions'
    | '/_app/h/$householdId/recalc'
    | '/_app/h/$householdId/recurring-rules'
    | '/_app/h/$householdId/report'
    | '/_app/h/$householdId/settings'
    | '/_app/h/$householdId/tags'
    | '/_app/h/$householdId/transactions'
    | '/_app/h/$householdId/'
    | '/_app/h/$householdId/report/categories'
    | '/_app/h/$householdId/report/insights'
    | '/_app/h/$householdId/report/obligations'
    | '/_app/h/$householdId/report/savings'
    | '/_app/h/$householdId/report/year'
    | '/_app/h/$householdId/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform': {
      id: '/_app/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mfa': {
      id: '/_auth/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/h/$householdId': {
      id: '/_app/h/$householdId'
      path: '/h/$householdId'
      fullPath: '/h/$householdId'
      preLoaderRoute: typeof AppHHouseholdIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/': {
      id: '/_app/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AppPlatformIndexRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/announcements': {
      id: '/_app/platform/announcements'
      path: '/announcements'
      fullPath: '/platform/announcements'
      preLoaderRoute: typeof AppPlatformAnnouncementsRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/config': {
      id: '/_app/platform/config'
      path: '/config'
      fullPath: '/platform/config'
      preLoaderRoute: typeof AppPlatformConfigRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/health': {
      id: '/_app/platform/health'
      path: '/health'
      fullPath: '/platform/health'
      preLoaderRoute: typeof AppPlatformHealthRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/rates': {
      id: '/_app/platform/rates'
      path: '/rates'
      fullPath: '/platform/rates'
      preLoaderRoute: typeof AppPlatformRatesRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_app/platform/users': {
      id: '/_app/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AppPlatformUsersRouteImport
      parentRoute: typeof AppPlatformRoute
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/h/$householdId/': {
      id: '/_app/h/$householdId/'
      path: '/'
      fullPath: '/h/$householdId/'
      preLoaderRoute: typeof AppHHouseholdIdIndexRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/accounts': {
      id: '/_app/h/$householdId/accounts'
      path: '/accounts'
      fullPath: '/h/$householdId/accounts'
      preLoaderRoute: typeof AppHHouseholdIdAccountsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/audit': {
      id: '/_app/h/$householdId/audit'
      path: '/audit'
      fullPath: '/h/$householdId/audit'
      preLoaderRoute: typeof AppHHouseholdIdAuditRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/categories': {
      id: '/_app/h/$householdId/categories'
      path: '/categories'
      fullPath: '/h/$householdId/categories'
      preLoaderRoute: typeof AppHHouseholdIdCategoriesRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/debts': {
      id: '/_app/h/$householdId/debts'
      path: '/debts'
      fullPath: '/h/$householdId/debts'
      preLoaderRoute: typeof AppHHouseholdIdDebtsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/devices': {
      id: '/_app/h/$householdId/devices'
      path: '/devices'
      fullPath: '/h/$householdId/devices'
      preLoaderRoute: typeof AppHHouseholdIdDevicesRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/export': {
      id: '/_app/h/$householdId/export'
      path: '/export'
      fullPath: '/h/$householdId/export'
      preLoaderRoute: typeof AppHHouseholdIdExportRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/goals': {
      id: '/_app/h/$householdId/goals'
      path: '/goals'
      fullPath: '/h/$householdId/goals'
      preLoaderRoute: typeof AppHHouseholdIdGoalsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/health': {
      id: '/_app/h/$householdId/health'
      path: '/health'
      fullPath: '/h/$householdId/health'
      preLoaderRoute: typeof AppHHouseholdIdHealthRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/import': {
      id: '/_app/h/$householdId/import'
      path: '/import'
      fullPath: '/h/$householdId/import'
      preLoaderRoute: typeof AppHHouseholdIdImportRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/legacy': {
      id: '/_app/h/$householdId/legacy'
      path: '/legacy'
      fullPath: '/h/$householdId/legacy'
      preLoaderRoute: typeof AppHHouseholdIdLegacyRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/limits': {
      id: '/_app/h/$householdId/limits'
      path: '/limits'
      fullPath: '/h/$householdId/limits'
      preLoaderRoute: typeof AppHHouseholdIdLimitsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/notifications': {
      id: '/_app/h/$householdId/notifications'
      path: '/notifications'
      fullPath: '/h/$householdId/notifications'
      preLoaderRoute: typeof AppHHouseholdIdNotificationsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/plans': {
      id: '/_app/h/$householdId/plans'
      path: '/plans'
      fullPath: '/h/$householdId/plans'
      preLoaderRoute: typeof AppHHouseholdIdPlansRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/profile': {
      id: '/_app/h/$householdId/profile'
      path: '/profile'
      fullPath: '/h/$householdId/profile'
      preLoaderRoute: typeof AppHHouseholdIdProfileRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/quick-actions': {
      id: '/_app/h/$householdId/quick-actions'
      path: '/quick-actions'
      fullPath: '/h/$householdId/quick-actions'
      preLoaderRoute: typeof AppHHouseholdIdQuickActionsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/recalc': {
      id: '/_app/h/$householdId/recalc'
      path: '/recalc'
      fullPath: '/h/$householdId/recalc'
      preLoaderRoute: typeof AppHHouseholdIdRecalcRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/recurring-rules': {
      id: '/_app/h/$householdId/recurring-rules'
      path: '/recurring-rules'
      fullPath: '/h/$householdId/recurring-rules'
      preLoaderRoute: typeof AppHHouseholdIdRecurringRulesRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/report': {
      id: '/_app/h/$householdId/report'
      path: '/report'
      fullPath: '/h/$householdId/report'
      preLoaderRoute: typeof AppHHouseholdIdReportRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/settings': {
      id: '/_app/h/$householdId/settings'
      path: '/settings'
      fullPath: '/h/$householdId/settings'
      preLoaderRoute: typeof AppHHouseholdIdSettingsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/tags': {
      id: '/_app/h/$householdId/tags'
      path: '/tags'
      fullPath: '/h/$householdId/tags'
      preLoaderRoute: typeof AppHHouseholdIdTagsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/transactions': {
      id: '/_app/h/$householdId/transactions'
      path: '/transactions'
      fullPath: '/h/$householdId/transactions'
      preLoaderRoute: typeof AppHHouseholdIdTransactionsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/report/': {
      id: '/_app/h/$householdId/report/'
      path: '/'
      fullPath: '/h/$householdId/report/'
      preLoaderRoute: typeof AppHHouseholdIdReportIndexRouteImport
      parentRoute: typeof AppHHouseholdIdReportRoute
    }
    '/_app/h/$householdId/report/categories': {
      id: '/_app/h/$householdId/report/categories'
      path: '/categories'
      fullPath: '/h/$householdId/report/categories'
      preLoaderRoute: typeof AppHHouseholdIdReportCategoriesRouteImport
      parentRoute: typeof AppHHouseholdIdReportRoute
    }
    '/_app/h/$householdId/report/insights': {
      id: '/_app/h/$householdId/report/insights'
      path: '/insights'
      fullPath: '/h/$householdId/report/insights'
      preLoaderRoute: typeof AppHHouseholdIdReportInsightsRouteImport
      parentRoute: typeof AppHHouseholdIdReportRoute
    }
    '/_app/h/$householdId/report/obligations': {
      id: '/_app/h/$householdId/report/obligations'
      path: '/obligations'
      fullPath: '/h/$householdId/report/obligations'
      preLoaderRoute: typeof AppHHouseholdIdReportObligationsRouteImport
      parentRoute: typeof AppHHouseholdIdReportRoute
    }
    '/_app/h/$householdId/report/savings': {
      id: '/_app/h/$householdId/report/savings'
      path: '/savings'
      fullPath: '/h/$householdId/report/savings'
      preLoaderRoute: typeof AppHHouseholdIdReportSavingsRouteImport
      parentRoute: typeof AppHHouseholdIdReportRoute
    }
    '/_app/h/$householdId/report/year': {
      id: '/_app/h/$householdId/report/year'
      path: '/year'
      fullPath: '/h/$householdId/report/year'
      preLoaderRoute: typeof AppHHouseholdIdReportYearRouteImport
      parentRoute: typeof AppHHouseholdIdReportRoute
    }
  }
}

interface AppPlatformRouteChildren {
  AppPlatformAnnouncementsRoute: typeof AppPlatformAnnouncementsRoute
  AppPlatformConfigRoute: typeof AppPlatformConfigRoute
  AppPlatformHealthRoute: typeof AppPlatformHealthRoute
  AppPlatformRatesRoute: typeof AppPlatformRatesRoute
  AppPlatformUsersRoute: typeof AppPlatformUsersRoute
  AppPlatformIndexRoute: typeof AppPlatformIndexRoute
}

const AppPlatformRouteChildren: AppPlatformRouteChildren = {
  AppPlatformAnnouncementsRoute: AppPlatformAnnouncementsRoute,
  AppPlatformConfigRoute: AppPlatformConfigRoute,
  AppPlatformHealthRoute: AppPlatformHealthRoute,
  AppPlatformRatesRoute: AppPlatformRatesRoute,
  AppPlatformUsersRoute: AppPlatformUsersRoute,
  AppPlatformIndexRoute: AppPlatformIndexRoute,
}

const AppPlatformRouteWithChildren = AppPlatformRoute._addFileChildren(
  AppPlatformRouteChildren,
)

interface AppHHouseholdIdReportRouteChildren {
  AppHHouseholdIdReportCategoriesRoute: typeof AppHHouseholdIdReportCategoriesRoute
  AppHHouseholdIdReportInsightsRoute: typeof AppHHouseholdIdReportInsightsRoute
  AppHHouseholdIdReportObligationsRoute: typeof AppHHouseholdIdReportObligationsRoute
  AppHHouseholdIdReportSavingsRoute: typeof AppHHouseholdIdReportSavingsRoute
  AppHHouseholdIdReportYearRoute: typeof AppHHouseholdIdReportYearRoute
  AppHHouseholdIdReportIndexRoute: typeof AppHHouseholdIdReportIndexRoute
}

const AppHHouseholdIdReportRouteChildren: AppHHouseholdIdReportRouteChildren = {
  AppHHouseholdIdReportCategoriesRoute: AppHHouseholdIdReportCategoriesRoute,
  AppHHouseholdIdReportInsightsRoute: AppHHouseholdIdReportInsightsRoute,
  AppHHouseholdIdReportObligationsRoute: AppHHouseholdIdReportObligationsRoute,
  AppHHouseholdIdReportSavingsRoute: AppHHouseholdIdReportSavingsRoute,
  AppHHouseholdIdReportYearRoute: AppHHouseholdIdReportYearRoute,
  AppHHouseholdIdReportIndexRoute: AppHHouseholdIdReportIndexRoute,
}

const AppHHouseholdIdReportRouteWithChildren =
  AppHHouseholdIdReportRoute._addFileChildren(
    AppHHouseholdIdReportRouteChildren,
  )

interface AppHHouseholdIdRouteChildren {
  AppHHouseholdIdAccountsRoute: typeof AppHHouseholdIdAccountsRoute
  AppHHouseholdIdAuditRoute: typeof AppHHouseholdIdAuditRoute
  AppHHouseholdIdCategoriesRoute: typeof AppHHouseholdIdCategoriesRoute
  AppHHouseholdIdDebtsRoute: typeof AppHHouseholdIdDebtsRoute
  AppHHouseholdIdDevicesRoute: typeof AppHHouseholdIdDevicesRoute
  AppHHouseholdIdExportRoute: typeof AppHHouseholdIdExportRoute
  AppHHouseholdIdGoalsRoute: typeof AppHHouseholdIdGoalsRoute
  AppHHouseholdIdHealthRoute: typeof AppHHouseholdIdHealthRoute
  AppHHouseholdIdImportRoute: typeof AppHHouseholdIdImportRoute
  AppHHouseholdIdLegacyRoute: typeof AppHHouseholdIdLegacyRoute
  AppHHouseholdIdLimitsRoute: typeof AppHHouseholdIdLimitsRoute
  AppHHouseholdIdNotificationsRoute: typeof AppHHouseholdIdNotificationsRoute
  AppHHouseholdIdPlansRoute: typeof AppHHouseholdIdPlansRoute
  AppHHouseholdIdProfileRoute: typeof AppHHouseholdIdProfileRoute
  AppHHouseholdIdQuickActionsRoute: typeof AppHHouseholdIdQuickActionsRoute
  AppHHouseholdIdRecalcRoute: typeof AppHHouseholdIdRecalcRoute
  AppHHouseholdIdRecurringRulesRoute: typeof AppHHouseholdIdRecurringRulesRoute
  AppHHouseholdIdReportRoute: typeof AppHHouseholdIdReportRouteWithChildren
  AppHHouseholdIdSettingsRoute: typeof AppHHouseholdIdSettingsRoute
  AppHHouseholdIdTagsRoute: typeof AppHHouseholdIdTagsRoute
  AppHHouseholdIdTransactionsRoute: typeof AppHHouseholdIdTransactionsRoute
  AppHHouseholdIdIndexRoute: typeof AppHHouseholdIdIndexRoute
}

const AppHHouseholdIdRouteChildren: AppHHouseholdIdRouteChildren = {
  AppHHouseholdIdAccountsRoute: AppHHouseholdIdAccountsRoute,
  AppHHouseholdIdAuditRoute: AppHHouseholdIdAuditRoute,
  AppHHouseholdIdCategoriesRoute: AppHHouseholdIdCategoriesRoute,
  AppHHouseholdIdDebtsRoute: AppHHouseholdIdDebtsRoute,
  AppHHouseholdIdDevicesRoute: AppHHouseholdIdDevicesRoute,
  AppHHouseholdIdExportRoute: AppHHouseholdIdExportRoute,
  AppHHouseholdIdGoalsRoute: AppHHouseholdIdGoalsRoute,
  AppHHouseholdIdHealthRoute: AppHHouseholdIdHealthRoute,
  AppHHouseholdIdImportRoute: AppHHouseholdIdImportRoute,
  AppHHouseholdIdLegacyRoute: AppHHouseholdIdLegacyRoute,
  AppHHouseholdIdLimitsRoute: AppHHouseholdIdLimitsRoute,
  AppHHouseholdIdNotificationsRoute: AppHHouseholdIdNotificationsRoute,
  AppHHouseholdIdPlansRoute: AppHHouseholdIdPlansRoute,
  AppHHouseholdIdProfileRoute: AppHHouseholdIdProfileRoute,
  AppHHouseholdIdQuickActionsRoute: AppHHouseholdIdQuickActionsRoute,
  AppHHouseholdIdRecalcRoute: AppHHouseholdIdRecalcRoute,
  AppHHouseholdIdRecurringRulesRoute: AppHHouseholdIdRecurringRulesRoute,
  AppHHouseholdIdReportRoute: AppHHouseholdIdReportRouteWithChildren,
  AppHHouseholdIdSettingsRoute: AppHHouseholdIdSettingsRoute,
  AppHHouseholdIdTagsRoute: AppHHouseholdIdTagsRoute,
  AppHHouseholdIdTransactionsRoute: AppHHouseholdIdTransactionsRoute,
  AppHHouseholdIdIndexRoute: AppHHouseholdIdIndexRoute,
}

const AppHHouseholdIdRouteWithChildren = AppHHouseholdIdRoute._addFileChildren(
  AppHHouseholdIdRouteChildren,
)

interface AppRouteChildren {
  AppPlatformRoute: typeof AppPlatformRouteWithChildren
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHHouseholdIdRoute: typeof AppHHouseholdIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppPlatformRoute: AppPlatformRouteWithChildren,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppHHouseholdIdRoute: AppHHouseholdIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
