/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthMfaRouteImport } from './routes/_auth/mfa'
import { Route as AppHHouseholdIdRouteImport } from './routes/_app/h/$householdId'
import { Route as AuthAuthCallbackRouteImport } from './routes/_auth/auth/callback'
import { Route as AppHHouseholdIdIndexRouteImport } from './routes/_app/h/$householdId/index'
import { Route as AppHHouseholdIdAccountsRouteImport } from './routes/_app/h/$householdId/accounts'
import { Route as AppHHouseholdIdCategoriesRouteImport } from './routes/_app/h/$householdId/categories'
import { Route as AppHHouseholdIdDebtsRouteImport } from './routes/_app/h/$householdId/debts'
import { Route as AppHHouseholdIdGoalsRouteImport } from './routes/_app/h/$householdId/goals'
import { Route as AppHHouseholdIdLimitsRouteImport } from './routes/_app/h/$householdId/limits'
import { Route as AppHHouseholdIdProfileRouteImport } from './routes/_app/h/$householdId/profile'
import { Route as AppHHouseholdIdQuickActionsRouteImport } from './routes/_app/h/$householdId/quick-actions'
import { Route as AppHHouseholdIdRecurringRulesRouteImport } from './routes/_app/h/$householdId/recurring-rules'
import { Route as AppHHouseholdIdSettingsRouteImport } from './routes/_app/h/$householdId/settings'
import { Route as AppHHouseholdIdTagsRouteImport } from './routes/_app/h/$householdId/tags'
import { Route as AppHHouseholdIdTransactionsRouteImport } from './routes/_app/h/$householdId/transactions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AppHHouseholdIdRoute = AppHHouseholdIdRouteImport.update({
  id: '/h/$householdId',
  path: '/h/$householdId',
  getParentRoute: () => AppRoute,
} as any)
const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AppHHouseholdIdIndexRoute = AppHHouseholdIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdAccountsRoute = AppHHouseholdIdAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdCategoriesRoute =
  AppHHouseholdIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdDebtsRoute = AppHHouseholdIdDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdGoalsRoute = AppHHouseholdIdGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdLimitsRoute = AppHHouseholdIdLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdProfileRoute = AppHHouseholdIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdQuickActionsRoute =
  AppHHouseholdIdQuickActionsRouteImport.update({
    id: '/quick-actions',
    path: '/quick-actions',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdRecurringRulesRoute =
  AppHHouseholdIdRecurringRulesRouteImport.update({
    id: '/recurring-rules',
    path: '/recurring-rules',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)
const AppHHouseholdIdSettingsRoute = AppHHouseholdIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdTagsRoute = AppHHouseholdIdTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppHHouseholdIdRoute,
} as any)
const AppHHouseholdIdTransactionsRoute =
  AppHHouseholdIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AppHHouseholdIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/welcome': typeof AppWelcomeRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/h/$householdId': typeof AppHHouseholdIdRouteWithChildren
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/h/$householdId/accounts': typeof AppHHouseholdIdAccountsRoute
  '/h/$householdId/categories': typeof AppHHouseholdIdCategoriesRoute
  '/h/$householdId/debts': typeof AppHHouseholdIdDebtsRoute
  '/h/$householdId/goals': typeof AppHHouseholdIdGoalsRoute
  '/h/$householdId/limits': typeof AppHHouseholdIdLimitsRoute
  '/h/$householdId/profile': typeof AppHHouseholdIdProfileRoute
  '/h/$householdId/quick-actions': typeof AppHHouseholdIdQuickActionsRoute
  '/h/$householdId/recurring-rules': typeof AppHHouseholdIdRecurringRulesRoute
  '/h/$householdId/settings': typeof AppHHouseholdIdSettingsRoute
  '/h/$householdId/tags': typeof AppHHouseholdIdTagsRoute
  '/h/$householdId/transactions': typeof AppHHouseholdIdTransactionsRoute
  '/h/$householdId/': typeof AppHHouseholdIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/welcome': typeof AppWelcomeRoute
  '/login': typeof AuthLoginRoute
  '/mfa': typeof AuthMfaRoute
  '/auth/callback': typeof AuthAuthCallbackRoute
  '/h/$householdId/accounts': typeof AppHHouseholdIdAccountsRoute
  '/h/$householdId/categories': typeof AppHHouseholdIdCategoriesRoute
  '/h/$householdId/debts': typeof AppHHouseholdIdDebtsRoute
  '/h/$householdId/goals': typeof AppHHouseholdIdGoalsRoute
  '/h/$householdId/limits': typeof AppHHouseholdIdLimitsRoute
  '/h/$householdId/profile': typeof AppHHouseholdIdProfileRoute
  '/h/$householdId/quick-actions': typeof AppHHouseholdIdQuickActionsRoute
  '/h/$householdId/recurring-rules': typeof AppHHouseholdIdRecurringRulesRoute
  '/h/$householdId/settings': typeof AppHHouseholdIdSettingsRoute
  '/h/$householdId/tags': typeof AppHHouseholdIdTagsRoute
  '/h/$householdId/transactions': typeof AppHHouseholdIdTransactionsRoute
  '/h/$householdId': typeof AppHHouseholdIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/welcome': typeof AppWelcomeRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/mfa': typeof AuthMfaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/h/$householdId': typeof AppHHouseholdIdRouteWithChildren
  '/_auth/auth/callback': typeof AuthAuthCallbackRoute
  '/_app/h/$householdId/accounts': typeof AppHHouseholdIdAccountsRoute
  '/_app/h/$householdId/categories': typeof AppHHouseholdIdCategoriesRoute
  '/_app/h/$householdId/debts': typeof AppHHouseholdIdDebtsRoute
  '/_app/h/$householdId/goals': typeof AppHHouseholdIdGoalsRoute
  '/_app/h/$householdId/limits': typeof AppHHouseholdIdLimitsRoute
  '/_app/h/$householdId/profile': typeof AppHHouseholdIdProfileRoute
  '/_app/h/$householdId/quick-actions': typeof AppHHouseholdIdQuickActionsRoute
  '/_app/h/$householdId/recurring-rules': typeof AppHHouseholdIdRecurringRulesRoute
  '/_app/h/$householdId/settings': typeof AppHHouseholdIdSettingsRoute
  '/_app/h/$householdId/tags': typeof AppHHouseholdIdTagsRoute
  '/_app/h/$householdId/transactions': typeof AppHHouseholdIdTransactionsRoute
  '/_app/h/$householdId/': typeof AppHHouseholdIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/login'
    | '/mfa'
    | '/h/$householdId'
    | '/auth/callback'
    | '/h/$householdId/accounts'
    | '/h/$householdId/categories'
    | '/h/$householdId/debts'
    | '/h/$householdId/goals'
    | '/h/$householdId/limits'
    | '/h/$householdId/profile'
    | '/h/$householdId/quick-actions'
    | '/h/$householdId/recurring-rules'
    | '/h/$householdId/settings'
    | '/h/$householdId/tags'
    | '/h/$householdId/transactions'
    | '/h/$householdId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/login'
    | '/mfa'
    | '/auth/callback'
    | '/h/$householdId/accounts'
    | '/h/$householdId/categories'
    | '/h/$householdId/debts'
    | '/h/$householdId/goals'
    | '/h/$householdId/limits'
    | '/h/$householdId/profile'
    | '/h/$householdId/quick-actions'
    | '/h/$householdId/recurring-rules'
    | '/h/$householdId/settings'
    | '/h/$householdId/tags'
    | '/h/$householdId/transactions'
    | '/h/$householdId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/welcome'
    | '/_auth/login'
    | '/_auth/mfa'
    | '/_app/'
    | '/_app/h/$householdId'
    | '/_auth/auth/callback'
    | '/_app/h/$householdId/accounts'
    | '/_app/h/$householdId/categories'
    | '/_app/h/$householdId/debts'
    | '/_app/h/$householdId/goals'
    | '/_app/h/$householdId/limits'
    | '/_app/h/$householdId/profile'
    | '/_app/h/$householdId/quick-actions'
    | '/_app/h/$householdId/recurring-rules'
    | '/_app/h/$householdId/settings'
    | '/_app/h/$householdId/tags'
    | '/_app/h/$householdId/transactions'
    | '/_app/h/$householdId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mfa': {
      id: '/_auth/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/h/$householdId': {
      id: '/_app/h/$householdId'
      path: '/h/$householdId'
      fullPath: '/h/$householdId'
      preLoaderRoute: typeof AppHHouseholdIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/auth/callback': {
      id: '/_auth/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/h/$householdId/': {
      id: '/_app/h/$householdId/'
      path: '/'
      fullPath: '/h/$householdId/'
      preLoaderRoute: typeof AppHHouseholdIdIndexRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/accounts': {
      id: '/_app/h/$householdId/accounts'
      path: '/accounts'
      fullPath: '/h/$householdId/accounts'
      preLoaderRoute: typeof AppHHouseholdIdAccountsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/categories': {
      id: '/_app/h/$householdId/categories'
      path: '/categories'
      fullPath: '/h/$householdId/categories'
      preLoaderRoute: typeof AppHHouseholdIdCategoriesRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/debts': {
      id: '/_app/h/$householdId/debts'
      path: '/debts'
      fullPath: '/h/$householdId/debts'
      preLoaderRoute: typeof AppHHouseholdIdDebtsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/goals': {
      id: '/_app/h/$householdId/goals'
      path: '/goals'
      fullPath: '/h/$householdId/goals'
      preLoaderRoute: typeof AppHHouseholdIdGoalsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/limits': {
      id: '/_app/h/$householdId/limits'
      path: '/limits'
      fullPath: '/h/$householdId/limits'
      preLoaderRoute: typeof AppHHouseholdIdLimitsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/profile': {
      id: '/_app/h/$householdId/profile'
      path: '/profile'
      fullPath: '/h/$householdId/profile'
      preLoaderRoute: typeof AppHHouseholdIdProfileRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/quick-actions': {
      id: '/_app/h/$householdId/quick-actions'
      path: '/quick-actions'
      fullPath: '/h/$householdId/quick-actions'
      preLoaderRoute: typeof AppHHouseholdIdQuickActionsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/recurring-rules': {
      id: '/_app/h/$householdId/recurring-rules'
      path: '/recurring-rules'
      fullPath: '/h/$householdId/recurring-rules'
      preLoaderRoute: typeof AppHHouseholdIdRecurringRulesRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/settings': {
      id: '/_app/h/$householdId/settings'
      path: '/settings'
      fullPath: '/h/$householdId/settings'
      preLoaderRoute: typeof AppHHouseholdIdSettingsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/tags': {
      id: '/_app/h/$householdId/tags'
      path: '/tags'
      fullPath: '/h/$householdId/tags'
      preLoaderRoute: typeof AppHHouseholdIdTagsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
    '/_app/h/$householdId/transactions': {
      id: '/_app/h/$householdId/transactions'
      path: '/transactions'
      fullPath: '/h/$householdId/transactions'
      preLoaderRoute: typeof AppHHouseholdIdTransactionsRouteImport
      parentRoute: typeof AppHHouseholdIdRoute
    }
  }
}

interface AppHHouseholdIdRouteChildren {
  AppHHouseholdIdAccountsRoute: typeof AppHHouseholdIdAccountsRoute
  AppHHouseholdIdCategoriesRoute: typeof AppHHouseholdIdCategoriesRoute
  AppHHouseholdIdDebtsRoute: typeof AppHHouseholdIdDebtsRoute
  AppHHouseholdIdGoalsRoute: typeof AppHHouseholdIdGoalsRoute
  AppHHouseholdIdLimitsRoute: typeof AppHHouseholdIdLimitsRoute
  AppHHouseholdIdProfileRoute: typeof AppHHouseholdIdProfileRoute
  AppHHouseholdIdQuickActionsRoute: typeof AppHHouseholdIdQuickActionsRoute
  AppHHouseholdIdRecurringRulesRoute: typeof AppHHouseholdIdRecurringRulesRoute
  AppHHouseholdIdSettingsRoute: typeof AppHHouseholdIdSettingsRoute
  AppHHouseholdIdTagsRoute: typeof AppHHouseholdIdTagsRoute
  AppHHouseholdIdTransactionsRoute: typeof AppHHouseholdIdTransactionsRoute
  AppHHouseholdIdIndexRoute: typeof AppHHouseholdIdIndexRoute
}

const AppHHouseholdIdRouteChildren: AppHHouseholdIdRouteChildren = {
  AppHHouseholdIdAccountsRoute: AppHHouseholdIdAccountsRoute,
  AppHHouseholdIdCategoriesRoute: AppHHouseholdIdCategoriesRoute,
  AppHHouseholdIdDebtsRoute: AppHHouseholdIdDebtsRoute,
  AppHHouseholdIdGoalsRoute: AppHHouseholdIdGoalsRoute,
  AppHHouseholdIdLimitsRoute: AppHHouseholdIdLimitsRoute,
  AppHHouseholdIdProfileRoute: AppHHouseholdIdProfileRoute,
  AppHHouseholdIdQuickActionsRoute: AppHHouseholdIdQuickActionsRoute,
  AppHHouseholdIdRecurringRulesRoute: AppHHouseholdIdRecurringRulesRoute,
  AppHHouseholdIdSettingsRoute: AppHHouseholdIdSettingsRoute,
  AppHHouseholdIdTagsRoute: AppHHouseholdIdTagsRoute,
  AppHHouseholdIdTransactionsRoute: AppHHouseholdIdTransactionsRoute,
  AppHHouseholdIdIndexRoute: AppHHouseholdIdIndexRoute,
}

const AppHHouseholdIdRouteWithChildren = AppHHouseholdIdRoute._addFileChildren(
  AppHHouseholdIdRouteChildren,
)

interface AppRouteChildren {
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHHouseholdIdRoute: typeof AppHHouseholdIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppHHouseholdIdRoute: AppHHouseholdIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
